# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Home', folder: '/', file: ''}
- {name: 'About', folder: 'pages/about', file: ''}
- {name: 'Resume', folder: 'assets', file: 'BowdenJames_Resume_08.20.pdf'}
- {name: 'Teaching', folder: 'pages/teaching', file: ''}
- {name: 'Bowden Bytes', folder: 'pages/bytes', file: ''}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'envelope', link: 'mailto:jbowden@caltech.edu'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/j-bowden/'}
- {icon: 'github', link: 'https://github.com/james-bowden'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
